// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: internal/protocol/control.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Gateway routing and WebRTC signaling. Data contains end-to-end TLS records.
type Packet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Session       string                 `protobuf:"bytes,4,opt,name=session,proto3" json:"session,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_internal_protocol_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_internal_protocol_control_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Packet) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Packet) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *Packet) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Packet) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_internal_protocol_control_proto protoreflect.FileDescriptor

const file_internal_protocol_control_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/control.proto\x12\n" +
	"control.v1\"n\n" +
	"\x06Packet\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x18\n" +
	"\asession\x18\x04 \x01(\tR\asession\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04dataB0Z.github.com/koltyakov/control/internal/protocolb\x06proto3"

var (
	file_internal_protocol_control_proto_rawDescOnce sync.Once
	file_internal_protocol_control_proto_rawDescData []byte
)

func file_internal_protocol_control_proto_rawDescGZIP() []byte {
	file_internal_protocol_control_proto_rawDescOnce.Do(func() {
		file_internal_protocol_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_control_proto_rawDesc), len(file_internal_protocol_control_proto_rawDesc)))
	})
	return file_internal_protocol_control_proto_rawDescData
}

var file_internal_protocol_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_control_proto_goTypes = []any{
	(*Packet)(nil), // 0: control.v1.Packet
}
var file_internal_protocol_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_control_proto_init() }
func file_internal_protocol_control_proto_init() {
	if File_internal_protocol_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_control_proto_rawDesc), len(file_internal_protocol_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_control_proto_goTypes,
		DependencyIndexes: file_internal_protocol_control_proto_depIdxs,
		MessageInfos:      file_internal_protocol_control_proto_msgTypes,
	}.Build()
	File_internal_protocol_control_proto = out.File
	file_internal_protocol_control_proto_goTypes = nil
	file_internal_protocol_control_proto_depIdxs = nil
}
